# version: "3.8"

# services:
#   nextjs-app:
#     image: potholio
#     container_name: nextjs-app
#     build:
#       context: .
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./app:/app
#       - node_modules:/app/node_modules
#       - build:/app/.next
#     env_file:
#       - .env
# volumes:
#   node_modules:

#   build:

# version: "3.8"
services:
  nextjs-app:
    image: potholio
    container_name: potholio
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/app:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    env_file:
      - .env

volumes:
  node_modules:
  build:
